### ISSUE TITLE
Image is cut

### ISSUE THREAD

**Issue by mscherer82** [xclud/flutter_crop#13]
I've expected this plugin to work like the cropping function on e.g. instagram or other photo apps. 

Let me give you an example:
The app expects a certain format for phots, let's say a ascpect ration of 16:9. Now the user selects a portrait photo from his gallery. The cropping tool now allow you to select a part of the image which has to fit in the 16:9 frame.

When trying the crop demo I got another behavior: When starting the demo I can see the whole sample picture. When changing the aspect ration to 16:9 the top and bottom of the image is cut off. I'm not able to select the missing part of the picture anymore.

Is that the intended behaviour or is it a bug? If it is not clear what I mean I can provide screenshots.

**Comment by xclud** [comment]
Hi @mscherer82, can you please attach some screenshots and mark the areas you found the bug?

**Comment by mscherer82** [comment]
![grafik](https://user-images.githubusercontent.com/1001285/80800882-f9362d80-8baa-11ea-8604-a845b7def68c.png)

![grafik](https://user-images.githubusercontent.com/1001285/80800935-1cf97380-8bab-11ea-97b6-a27969cae9af.png)

On the first screenshot you can see two green bushes on the right side. After changing the aspect ratio this area is cut off.

**Comment by xclud** [comment]
I am not able to reproduce this bug. Can you attach a video/gif ?
Can you please provide detailed steps to reproduce this?

**Comment by Kimonnn** [comment]
I got it the same. Maybe you dont consider it as a bug but what he means is that the imagecropper changes the actual image size when selecting the aspect ratio instead of just changing the box size where you can move the image inside as you want. So the image cuts off to fit in the Box and you cannot move the image to select which part of the image should be chosen.

**Comment by seekcx** [comment]
I also encountered this problem, changing BoxFit is a solution, but it will make it impossible to limit the selection boundary.

**Comment by xclud** [comment]
This is definitely a bug. I am not able to reproduce this bug. Can you share some code or a video ?

**Comment by seekcx** [comment]
The example should be reproducible, but you need to choose a larger picture with a high aspect ratio.

**Comment by Kimonnn** [comment]
You can even see it in your demo app, select an other aspect ratio and the image gets cut to fit the box so you cannot move the image anymore

**Comment by Kimonnn** [comment]
i made a screen record: https://photos.google.com/share/AF1QipMtjEN2LA1Vq9HqHtJuRUMiYG9Vet1fleJtk_zhx7yv6HYnukVmu0w31O89Id9uwA/photo/AF1QipOi_e2XgpIj3YorzjRvKCByXQjB8sHip_dTZKJC?key=ZXBRUzhfWlUzbFZwd2lqajJWUXFieUE0aHFOYkF3

**Comment by xclud** [comment]
@Kimonnn thank you. I can see the bug now and will investigate it. I will let you all know when i make fix.

**Comment by Kimonnn** [comment]
you can also view it here (maybe a bit better): https://photos.google.com/share/AF1QipOraNatJSVkVwFwEeBEldJaksulPL8r66J1S6DSN2gL8z06WFWYjt7MdUSrb2CsWQ/photo/AF1QipNjWwMlSWMaoDD2P2YFhMjejE8lxgTaVt9sMGPw?key=SUVTYjFHeXlWck5nbUY2ZzZrVHlnR2E2VkNMaGx3

when I select 9:16 as an example, you can see that some parts of the image are unreachable then like the Vulcan at the right side, which is hidden then

when zooming in there is also no zoom limit so you can zoom endlessly which would be nice to cancel

**Comment by xclud** [comment]
@Kimonnn 

> when zooming in there is also no zoom limit so you can zoom endlessly which would be nice to cancel

This is a great suggestion. Would you create a separate issue for this. So we can receive ideas from other users and track the changes there.

**Comment by aloisdeniel** [comment]
I'm facing the same issue : he child widget is cropped to its initial size instead of overflowing.

**Comment by xclud** [comment]
@aloisdeniel Did you put an `Image` or another widget as a child?

**Comment by aloisdeniel** [comment]
It is a `CachedNetworkImage` behind the scene.

**Comment by aloisdeniel** [comment]
But if I use a fulfilled container with fixed dimensions, it behaves the same way.

![](https://i.imgur.com/xjf754B.gif)

**Comment by xclud** [comment]
Thank you everyone for reporting and helping the this issue. This is now fixed in version 0.3.2.

Can you guys verify if the package behaves as expected?

**Comment by stonega** [comment]
I tried 0.3.2, looks like the issue is still there, after changed the aspect ratio, the pic was croped.
```
 child: Crop(
                controller: controller,
                child: Image.file(
                  widget.image,
                  fit: BoxFit.cover,
                ),
                helper: Container(
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.white, width: 2),
                  ),
                ),
              ),
```

**Comment by xclud** [comment]
@stonega can you share a screenshot please?

**Comment by stonega** [comment]
https://photos.app.goo.gl/MHQLXzCUGNWP4FaZA

Thanks!

**Comment by xclud** [comment]
@stonega Sorry but i don't see anything wrong with your screen record. Can you give more details about the problem ?

**Comment by stonega** [comment]
@xclud I mean when I change the ratio, the pic was cut off, so I can't choose some part of the pic, only can zoom out.

**Comment by xclud** [comment]
@stonega This is the expected behavior. You may not crop a horizontal image with a vertical ratio unless you zoom in deep enough to cover the whole canvas. Thank you for your feedback :)

**Comment by stonega** [comment]
@xclud Thanks for your patience, what I really need in my app is to crop the square ratio of the image user picked just like Instagram, is it possible to use the plugin?

**Comment by xclud** [comment]
@stonega just put the ratio to 1 and do not allow the users change the ratio. This should work fine.

**Comment by stonega** [comment]
@xclud if I set the ratio to 1, then the pic just become squre, and can not be moved, so left or right part of the img can not be choosed, I must missed something.

**Comment by xclud** [comment]
If the image is square, then it fully fits the canvas as the canvas ratio is set 1 as well. There will be no room to move the pic left/right. This makes sense. But if the user wants to crop a part of the pic, they have to zoom in. I think in your case you should zoom in the canvas (pinch the screen). Do this work for you?

**Comment by stonega** [comment]
@xclud https://photos.app.goo.gl/oRZNn2LbHcRnXZf9A
The image I picked is not square, if zoom in , still only square part.
Do I need some extra setting maybe?

**Comment by xclud** [comment]
@stonega I am not getting your point and i am confused now. If you set the ratio to 1, this means you want a square part of the image.

**Comment by stonega** [comment]
@xclud yes, and I want to choose left part square or right part square, but what happened is that square is fixed part, can't be changed.

**Comment by xclud** [comment]
@stonega Then this means your picture is square as well. Can you attach the pic you are dealing with? Only if it's not private or personal.

**Comment by stonega** [comment]
https://photos.app.goo.gl/K5izKVtqBocvdQpW9
Here is the image.

**Comment by xclud** [comment]
Thank you. The image is not square so you must be able to drag let and right. I will check this out and let you know ASAP.

**Comment by stonega** [comment]
I tried wrap the image in the align widget, then it worked just as I thought somehow, but this must not the best solution.
Looking forward to your reply.
Thanks again!
```
Crop(
                controller: controller,
                child: Align(
                  widthFactor: 0.5,
                  child: Image.file(widget.image, fit: BoxFit.cover),
                ),
                helper: Container(
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.white, width: 2),
                  ),
                ),
              ),
```

**Comment by xclud** [comment]
I am closing this issue as it's fixed now.
